version: '3.8'

services:
  fe:
    container_name: pbl-fe
    restart: unless-stopped
    build: 
      context: book-lib-fe/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - "80:80"
    depends_on:
      - api
  api:
    container_name: pbl-api-backend
    environment:
      - SQLHOST=backend-db-1
      - SQLUSER=admin_db
      - SQLUSERPW=abcd1234
      - SQLDB=dev_db
      - SQLPORT=5432
      - SECRET=536140e0a6c9ac16ed3ec9a0ae793916eda09b13e8afcc73 # Change to HEX-16/32/64
    restart: unless-stopped
    build:
        context: backend/
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: dev_db
      TZ: UTC
    ports:
      - "5432:5432" # Expose PostgreSQL port for access from host SQL Client
    expose:
      - "5432:5432"
    volumes:
      - ./db/pgsql:/var/lib/postgresql/data

networks:
  default:
    name: Dev